# Helm chart values for the prod environment
daskhub:
  jupyterhub:
    hub:
  # this allows the dask-gateway pods to talk to the hub
      networkPolicy:
        ingress:
          - ports:
            - port: https
            from:
              - podSelector:
                  matchLabels:
                    gateway.dask.org/instance: "laika-dask-gateway"
    # this allows dask-gateway pods to talk to the proxy and autohttps pods
    proxy:
      chp:
        networkPolicy:
          ingress:
            - ports:
              - port: https
              from:
                - podSelector:
                    matchLabels:
                      gateway.dask.org/instance: "laika-dask-gateway"
      traefik:
        networkPolicy:
          ingress:
            - ports:
              - port: https
              from:
                - podSelector:
                    matchLabels:
                      gateway.dask.org/instance: "laika-dask-gateway"
